# Generated by Django 5.1.6 on 2025-03-25 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(default='User', max_length=225)),
                ('last_name', models.CharField(max_length=225)),
                ('email', models.EmailField(max_length=225, unique=True)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('role', models.CharField(choices=[('Manager', 'Manager'), ('Employ', 'Employee'), ('Admin', 'Admin')], default='Employee', max_length=20)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('can_create_tasks', models.BooleanField(default=False)),
                ('can_assign_tasks', models.BooleanField(default=False)),
                ('can_view_all_tasks', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
